[package]
name = "archive"
version = "0.1.0"
authors = ["Patract <https://github.com/patractlabs>"]
edition = "2018"
description = "Synchronize the substrate-backed chain to index all Blocks, State, and Extrinsic data."

[workspace]
members = [
  "client",
  "kafka",
  "postgres",
  "actor",
]

[patch.crates-io]
# Client
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-executor-common = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-state-db = { git = "https://github.com/paritytech/substrate", branch = "master" }
# Primitives
sp-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-database = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-externalities = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-wasm-interface = { git = "https://github.com/paritytech/substrate", branch = "master" }

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
chrono = "0.4"
futures = "0.3"
fern = { version = "0.6", features = ["colored"] }
flume = "0.10"
log = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
structopt = { version = "0.3", features = ["suggestions", "color"] }
thiserror = "1.0"
tokio = { version = "1.5", features = ["rt-multi-thread"] }
toml = "0.5"

codec = { package = "parity-scale-codec", version = "2.0", features = ["derive", "full"] }

archive-client = { path = "./client" }
archive-postgres = { path = "./postgres" }
archive-kafka = { path = "./kafka" }
#archive-actor = { path = "./actor" }
