################################
# Archive logger configuration #
################################
[logger]
## Optional log level of console, default: "DEBUG"
console = { level = "DEBUG" }
## Optional log level of file, default: "DEBUG"
## Optional log file path, default: "./archive.log"
#file = { level = "DEBUG", path = "./polkadot-archive.log" }

################################
# Archive client configuration #
################################
[client]
## Directory where local WASM runtimes live. These runtimes take precedence
## over on-chain runtimes when the spec version matches. Disable overrides by default.
#wasm_runtime_overrides = "./wasm_runtime"

## RocksDB backend configuration for archive client
[client.rocksdb]
path = "../polkadot/database/chains/polkadot/db"
#max_open_files = 16
cache_size = 128
secondary_db_path = "./rocksdb_secondary"

[client.executor]
wasm_exec_method = "Compiled" # or "Interpreted"
default_heap_pages = 4096
max_runtime_instances = 32

###################################
# Archive scheduler configuration #
###################################
[scheduler]
#start_block = 0
max_block_load = 100
interval_ms = 1000

##################################
# Archive postgres configuration #
##################################
[postgres]
uri = "postgres://koushiro:koushiro123@localhost:5432/polkadot-archive"
min_connections = 2
max_connections = 8
connect_timeout = 10
disable_statement_logging = false

####################################
# Archive dispatcher configuration #
####################################
[dispatcher.kafka]
queue_timeout = 0
[dispatcher.kafka.topic]
metadata = "polkadot-metadata"
block = "polkadot-block"
finalized_block = "polkadot-finalized-block"
## https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
##
## https://stackoverflow.com/questions/59322133/kafka-broker-message-size-too-large
## https://kafka.apache.org/documentation/
## Broker:
##   `message.max.bytes`: default 1048588 (1 MB)
##   `replica.fetch.max.bytes`: default 1048576 (1 MiB)
## Producer:
##   `message.max.bytes`: default 1048576 (1 MiB)
## Consumer:
##   `max.partition.fetch.bytes`: default 1048576 (1 MiB)
##   `fetch.max.bytes`: default 57671680 (55 MiB)
[dispatcher.kafka.rdkafka]
"metadata.broker.list" = "localhost:9092" # or "bootstrap.servers" = "localhost:9092"
"compression.codec" = "none" # "none" | "gzip" | "lz4"
"message.max.bytes" = "134217728" # 128 MB
