name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build 
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
        toolchain: [nightly-2021-04-20]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Cache Build Output
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check Code Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Code Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p archive-postgres -p archive-kafka --all-features --all-targets -- -D warnings
